### ISSUE TITLE
Auto-generated RelayCommandGenerator

### ISSUE THREAD

**Issue by 0nly1ken0bi** [dotnet-presentations/dotnet-maui-workshop#86]
Following Part 2 - MVVM in the README.md

Where [ICommand] was replaced by [RelayCommand] in the MonkeysViewModel.cs file.  The current auto-generated code in Dependencies should be as follows:

`// <auto-generated/>
#pragma warning disable
#nullable enable
namespace MonkeyFinder.ViewModel
{
    partial class MonkeysViewModel
    {
        /// <summary>The backing field for <see cref="GetMonkeysASyncCommand"/>.</summary>
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator", "8.0.0.0")]
        private global::CommunityToolkit.Mvvm.Input.AsyncRelayCommand? getMonkeysASyncCommand;
        /// <summary>Gets an <see cref="global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand"/> instance wrapping <see cref="GetMonkeysASync"/>.</summary>
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator", "8.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand GetMonkeysASyncCommand => getMonkeysASyncCommand ??= new global::CommunityToolkit.Mvvm.Input.AsyncRelayCommand(new global::System.Func<global::System.Threading.Tasks.Task>(GetMonkeysASync));
    }
}`

**Comment by jamesmontemagno** [comment]
fixed up

**Comment by Ezema-Ugonna-Donald** [comment]
I'm still getting the following as my generated code:
`/// <summary>The backing field for <see cref="GetMonkeysAysncCommand"/>.</summary>
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator", "8.0.0.0")]
        private global::CommunityToolkit.Mvvm.Input.AsyncRelayCommand? getMonkeysAysncCommand;
        /// <summary>Gets an <see cref="global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand"/> instance wrapping <see cref="GetMonkeysAysnc"/>.</summary>
        [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator", "8.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand GetMonkeysAysncCommand => getMonkeysAysncCommand ??= new global::CommunityToolkit.Mvvm.Input.AsyncRelayCommand(new global::System.Func<global::System.Threading.Tasks.Task>(GetMonkeysAysnc));`
